const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"班级类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBanji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"帖子类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryForum"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"通知类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"活动类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuodong"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"投票类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueshengToupiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"职位类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiwei"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"通知管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"通知管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"活动管理",
                        "menuJump":"列表",
                        "tableName":"huodong"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"活动留言管理",
                        "menuJump":"列表",
                        "tableName":"huodongLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"活动收藏管理",
                        "menuJump":"列表",
                        "tableName":"huodongCollection"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"活动报名管理",
                        "menuJump":"列表",
                        "tableName":"huodongYuyue"
                    }
                ],
                "menu":"活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"干部管理",
                        "menuJump":"列表",
                        "tableName":"ganbu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"xueshengKaoqin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "删除"
                        ],
                        "menu":"考勤详情管理",
                        "menuJump":"列表",
                        "tableName":"xueshengKaoqinList"
                    }
                ],
                "menu":"考勤管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"投票管理",
                        "menuJump":"列表",
                        "tableName":"xueshengToupiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "删除"
                        ],
                        "menu":"投票详情管理",
                        "menuJump":"列表",
                        "tableName":"xueshengToupiaoList"
                    }
                ],
                "menu":"投票管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"通知管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"通知管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"活动管理",
                        "menuJump":"列表",
                        "tableName":"huodong"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"活动留言管理",
                        "menuJump":"列表",
                        "tableName":"huodongLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"活动收藏管理",
                        "menuJump":"列表",
                        "tableName":"huodongCollection"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"活动报名管理",
                        "menuJump":"列表",
                        "tableName":"huodongYuyue"
                    }
                ],
                "menu":"活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"xueshengKaoqin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "报表"
                        ],
                        "menu":"考勤详情管理",
                        "menuJump":"列表",
                        "tableName":"xueshengKaoqinList"
                    }
                ],
                "menu":"考勤管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"投票管理",
                        "menuJump":"列表",
                        "tableName":"xueshengToupiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "报表"
                        ],
                        "menu":"投票详情管理",
                        "menuJump":"列表",
                        "tableName":"xueshengToupiaoList"
                    }
                ],
                "menu":"投票管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"干部",
        "tableName":"ganbu"
    }
]
    }
}
export default menu;
